#!/usr/bin/env python3
"""Extract Screen-separated mutants (B2 accept, M reject).

Default: industrial prevention_full_v1.
Pass --jsonl / --out-tex for external corpora.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DEFAULT_JSONL = ROOT / "artifacts" / "prevention_eval" / "prevention_full_v1" / "prevention_eval.jsonl"
DEFAULT_OUT_JSON = ROOT / "paper" / "hsp-agile" / "data" / "processed" / "e2_screen_hit_vignettes.json"
DEFAULT_OUT_TEX = ROOT / "paper" / "hsp-agile" / "tables" / "e2_screen_vignette.tex"

HARD_PREFIX = "HardSynthetic"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--jsonl", type=Path, default=DEFAULT_JSONL)
    ap.add_argument("--out-json", type=Path, default=DEFAULT_OUT_JSON)
    ap.add_argument("--out-tex", type=Path, default=DEFAULT_OUT_TEX)
    ap.add_argument("--label", type=str, default="industrial-style")
    ap.add_argument("--include-hard", action="store_true")
    args = ap.parse_args()

    by: dict[tuple, dict[str, dict]] = defaultdict(dict)
    with args.jsonl.open(encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("eval_type") != "impl_screening":
                continue
            key = (r["task_id"], r["mutant_id"], r["operator"])
            by[key][r["mode"]] = r

    vignettes = []
    for key, modes in by.items():
        task_id, mutant_id, op = key
        if (not args.include_hard) and task_id.startswith(HARD_PREFIX):
            continue
        b2, m, a2 = modes.get("B2"), modes.get("M"), modes.get("A2")
        if not b2 or not m:
            continue
        if b2.get("accepted") and not m.get("accepted"):
            vignettes.append(
                {
                    "task_id": task_id,
                    "mutant_id": mutant_id,
                    "operator": op,
                    "description": b2.get("description"),
                    "b2_accepted": True,
                    "a2_accepted": bool(a2.get("accepted")) if a2 else None,
                    "m_accepted": False,
                    "b2_strict": b2.get("strict_conformance"),
                    "m_strict": m.get("strict_conformance"),
                    "a2_strict": a2.get("strict_conformance") if a2 else None,
                    "reading": (
                        "Witness Conf.=1 under B2/A2/M; Screen in M rejects the "
                        "mutant that B2/A2 falsely accept."
                    ),
                }
            )

    ops = Counter(v["operator"] for v in vignettes)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "source": str(args.jsonl.as_posix()),
        "n_screen_hits": len(vignettes),
        "operator_counts": dict(ops),
        "vignettes": vignettes,
        "examples": [v for v in vignettes if v["operator"] in ("DRO", "MBO", "WRO")][:6],
    }
    args.out_json.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    picks = []
    for want in ("DRO", "MBO", "WRO"):
        for v in vignettes:
            if v["operator"] == want and v not in picks:
                picks.append(v)
                break
    while len(picks) < 3 and len(vignettes) > len(picks):
        for v in vignettes:
            if v not in picks:
                picks.append(v)
            if len(picks) >= 3:
                break

    def esc(s: str) -> str:
        return (s or "").replace("_", "\\_").replace("%", "\\%")

    rows = " \\\\\n".join(
        f"{esc(v['task_id'])} & {v['operator']} & "
        f"{esc((v['description'] or '')[:48])} & "
        f"B2/A2 accept, M reject"
        for v in picks
    )
    tex = f"""% Auto-generated by scripts/e2_screen_hit_vignettes.py
\\begin{{table}}[t]
  \\centering
  \\caption{{Screen-hit vignettes on {args.label} mutants.
    All {len(vignettes)} cases where B2 accepts and M rejects share Conf.${{=}}1$
    under B2/A2/M; the second gate alone separates them.
    Operators: DRO = remove else/catch-all branch; MBO = off-by-one comparison;
    WRO = wrong relational operator.}}
  \\label{{tab:e2-screen-vignette}}
  \\footnotesize
  \\begin{{tabular}}{{@{{}}lll@{{ }}p{{0.28\\linewidth}}@{{}}}}
    \\toprule
    Task & Op & Defect sketch & Gate outcome \\\\
    \\midrule
{rows} \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(tex, encoding="utf-8")
    print(json.dumps({"n": len(vignettes), "ops": dict(ops), "picks": [p["mutant_id"] for p in picks]}, indent=2))


if __name__ == "__main__":
    main()
