#!/usr/bin/env python3
"""Code E6 C-A wins and losses from run_feedback_v2 results.jsonl."""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]  # paper/hsp-agile
ROOT = PAPER.parents[1]  # repo root
RESULTS = ROOT / "artifacts/run_feedback_v2/feedback_variants/results.jsonl"
OUT_JSON = PAPER / "data/processed/e6_win_loss_coding.json"
OUT_TEX = PAPER / "tables/e6_win_loss_coding.tex"
OUT_MAP = PAPER / "tables/defect_evidence_map.tex"


def summarize_fb(row: dict) -> tuple[Counter, Counter, int]:
    sfs = row.get("semantic_feedback") or []
    if isinstance(sfs, dict):
        sfs = [sfs]
    vtypes: Counter = Counter()
    scens: Counter = Counter()
    for fb in sfs:
        if not isinstance(fb, dict):
            continue
        vtypes[str(fb.get("violation_type", "?"))] += 1
        scens[str(fb.get("scenario_index", "?"))] += 1
    return vtypes, scens, len(sfs)


def main() -> None:
    by: dict[str, dict] = defaultdict(dict)
    for line in RESULTS.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        by[r["task_id"]][r["feedback_variant"]] = r

    wins, losses, ties = [], [], []
    for tid, m in by.items():
        a = float(m["test_only"]["formal_conformance"])
        c = float(m["semantic_ir"]["formal_conformance"])
        if c > a + 1e-12:
            wins.append((tid, a, c, c - a, m["semantic_ir"]))
        elif a > c + 1e-12:
            losses.append((tid, a, c, c - a, m["semantic_ir"]))
        else:
            ties.append((tid, c))

    win_v: Counter = Counter()
    win_s: Counter = Counter()
    zero_a = 0
    win_rows = []
    for tid, a, c, d, row in wins:
        if a <= 1e-12:
            zero_a += 1
        vt, sc, n = summarize_fb(row)
        win_v.update(vt)
        win_s.update(sc)
        win_rows.append(
            {
                "task_id": tid,
                "conf_a": a,
                "conf_c": c,
                "delta": d,
                "n_fb": n,
                "violation_types": dict(vt),
                "scenarios": dict(sc),
            }
        )

    loss_v: Counter = Counter()
    loss_s: Counter = Counter()
    loss_rows = []
    for tid, a, c, d, row in losses:
        vt, sc, n = summarize_fb(row)
        loss_v.update(vt)
        loss_s.update(sc)
        loss_rows.append(
            {
                "task_id": tid,
                "conf_a": a,
                "conf_c": c,
                "delta": d,
                "n_fb": n,
                "violation_types": dict(vt),
                "scenarios": dict(sc),
            }
        )

    partial = [t for t, c in ties if c < 1 - 1e-12]
    out = {
        "wlt": [len(wins), len(losses), len(ties)],
        "wins_zero_a": zero_a,
        "win_violation_types": dict(win_v),
        "win_scenarios": {str(k): v for k, v in win_s.items()},
        "loss_violation_types": dict(loss_v),
        "loss_scenarios": {str(k): v for k, v in loss_s.items()},
        "ties_partial_lt1": len(partial),
        "wins": win_rows,
        "losses": loss_rows,
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(out, indent=2), encoding="utf-8")

    top_win_v = win_v.most_common(1)[0][0] if win_v else "arithmetic"
    top_win_s = win_s.most_common(1)[0][0] if win_s else "8"
    loss_v_str = ", ".join(f"{k}~{v}" for k, v in loss_v.most_common()) or "n/a"
    loss_s_str = ", ".join(f"{k}~{v}" for k, v in loss_s.most_common()) or "n/a"

    tex = "\n".join(
        [
            r"% Auto-generated by scripts/e6_win_loss_coding.py — do not hand-edit.",
            r"\begin{table}[t]",
            r"  \centering",
            r"  \caption{E6 C$-$A win/\textbf{loss} coding"
            r" (\texttt{run\_feedback\_v2}, $n{=}120$)."
            r" Wins: scenario-indexed IR rescues collapsed test-only Conf."
            r" (dominant \texttt{others}/arithmetic)."
            r" Losses ($n{=}4$): IR does not dominate; no ordering-uniqueness claim.}",
            r"  \label{tab:e6-win-loss}",
            r"  \footnotesize",
            r"  \begin{tabular}{@{}lcc@{}}",
            r"    \toprule",
            r"    Signal & Wins ($n{=}14$) & Losses ($n{=}4$) \\",
            r"    \midrule",
            f"    Mean $\\Delta$Conf.\\ (pp) & $+7.7$ (overall) & negative subset \\\\",
            f"    test\\_only Conf$=0$ & {zero_a}/14 & --- \\\\",
            f"    Dominant \\texttt{{violation\\_type}} & {top_win_v} & {loss_v_str} \\\\",
            f"    Dominant \\texttt{{scenario\\_index}} & {top_win_s} (\\texttt{{others}}) & {loss_s_str} \\\\",
            r"    Ties (incl.\ near-ceiling) & \multicolumn{2}{c}{102/120} \\",
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
            "",
        ]
    )
    OUT_TEX.write_text(tex, encoding="utf-8")

    # Evidence map: which claim rests on which defect class
    map_tex = r"""% Hand-maintained evidence map (P0 accept push).
\begin{table}[t]
  \centering
  \caption{\textbf{Defect-class $\leftrightarrow$ evidence map.}
    Ordering/preemption defects motivate $\Phi_i$ witnesses and E2 mutants;
    E6's Conf.\ gain is a scenario-indexed \emph{rescue} under collapsed
    unstructured feedback (catch-all \texttt{others}/arithmetic), not an
    ordering-uniqueness proof on BENCH-120.}
  \label{tab:defect-evidence-map}
  \footnotesize
  \renewcommand{\arraystretch}{1.12}
  \begin{tabular}{@{}p{0.22\linewidth}p{0.28\linewidth}p{0.40\linewidth}@{}}
    \toprule
    \textbf{Defect class} & \textbf{Primary evidence} & \textbf{What it supports} \\
    \midrule
    Guard-order / preemption
      & Motivating example; $\Phi_i$ design; E2 SNO/ORO/WRO mutants
      & C3 gate + witness necessity (not E6 win set) \\
    Catch-all \texttt{others} / output arithmetic
      & E6 win coding (14/14 arithmetic @ scen.~8); C$-$A rescue
      & C2 vs.\ unstructured dumps under headroom \\
    Boundary / relop
      & Hard combo-seed (gemini $n{=}80$); E9 historical residual
      & Supporting C2 under harder injected bugs \\
    Saturated easy endpoints
      & Industrial-pattern $n{=}31$; desens.\ $n{=}28$; GitHub $n{=}48$; HKCA09 $n{=}35$
      & C4 default B2 (often B2${=}$\texttt{M\_eq}) \\
    \bottomrule
  \end{tabular}
\end{table}
"""
    OUT_MAP.write_text(map_tex, encoding="utf-8")
    print(json.dumps({k: out[k] for k in out if k not in ("wins", "losses")}, indent=2))
    print(f"Wrote {OUT_TEX}")
    print(f"Wrote {OUT_MAP}")
    print(f"Wrote {OUT_JSON}")


if __name__ == "__main__":
    main()
