#!/usr/bin/env python3
"""Emit E6 win-profile table from Agent A qualitative artifacts (no LLM).

Inputs (existing):
  artifacts/strengthening_sprint/agent_a_evidence/e6_win_qualitative.json
  data/processed/e6_paired_summary.json (optional; for W/L/T)

Outputs:
  tables/e6_win_profile.tex
  data/processed/e6_win_profile.json
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

PAPER = Path(__file__).resolve().parents[1]
ROOT = PAPER.parents[1]
QUAL = (
    PAPER
    / "artifacts"
    / "strengthening_sprint"
    / "agent_a_evidence"
    / "e6_win_qualitative.json"
)
PAIRED = PAPER / "data" / "processed" / "e6_paired_summary.json"
OUT_TEX = PAPER / "tables" / "e6_win_profile.tex"
OUT_JSON = PAPER / "data" / "processed" / "e6_win_profile.json"


WIN_TASKS = (
    PAPER
    / "artifacts"
    / "strengthening_sprint"
    / "agent_a_evidence"
    / "e6_win_tasks.json"
)


def main() -> None:
    raw = json.loads(QUAL.read_text(encoding="utf-8"))
    win_ids = set()
    if WIN_TASKS.exists():
        win_ids = set(json.loads(WIN_TASKS.read_text(encoding="utf-8")).get(
            "semantic_ir_wins", []
        ))
    if win_ids:
        wins = [w for w in raw if w.get("task_id") in win_ids]
    else:
        wins = [
            w
            for w in raw
            if float(w.get("delta", 0)) > 1e-9
            or float(w.get("conf_ir", 0))
            > float(w.get("conf_test_only", 0)) + 1e-9
        ]
    if not wins:
        wins = raw
    n_wins = len(wins)
    zero_a = sum(1 for w in wins if float(w.get("conf_test_only", 1)) <= 1e-12)
    vtypes = Counter()
    scen = Counter()
    for w in wins:
        fb = w.get("sample_feedback") or {}
        vtypes[str(fb.get("violation_type", "unknown"))] += 1
        scen[str(fb.get("scenario_index", "?"))] += 1
        # Also count from ir_cat_counts if present
        for k, c in (w.get("ir_cat_counts") or {}).items():
            pass  # sample_feedback is the paper-facing signal

    paired = {}
    if PAIRED.exists():
        paired = json.loads(PAIRED.read_text(encoding="utf-8"))
    ca = {}
    for row in paired.get("comparisons") or []:
        if row.get("comparator") == "test_only":
            ca = row
            break

    wins = int(ca.get("wins", 14))
    losses = int(ca.get("losses", 4))
    ties = int(ca.get("ties", 102))
    wlt = f"{wins}/{losses}/{ties}"
    delta = float(ca.get("delta_pp", ca.get("mean_delta_pp", 7.7)))
    delta = round(delta, 1)

    top_v = vtypes.most_common(1)[0][0] if vtypes else "arithmetic"
    top_s = scen.most_common(1)[0][0] if scen else "8"
    vtype_str = ", ".join(f"{k}~{v}/{n_wins}" for k, v in vtypes.most_common())
    scen_str = ", ".join(f"{k}~{v}/{n_wins}" for k, v in scen.most_common())

    profile = {
        "n_wins": n_wins,
        "zero_test_only": zero_a,
        "zero_frac": zero_a / n_wins if n_wins else 0,
        "violation_types": dict(vtypes),
        "scenario_indices": {str(k): v for k, v in scen.items()},
        "wlt": wlt,
        "delta_pp": delta,
        "note": (
            "E6 wins concentrate on catch-all/others output repair "
            "(arithmetic), not ordering-precedence wins on BENCH-120."
        ),
    }
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(profile, indent=2), encoding="utf-8")

    delta_tex = f"+{delta}"
    tex = "\n".join(
        [
            "% Auto-generated by scripts/e6_win_profile.py — do not hand-edit.",
            "% Source: agent_a_evidence/e6_win_qualitative.json + e6_paired_summary.json",
            r"\begin{table}[t]",
            r"  \centering",
            r"  \caption{E6 win profile (C$-$A wins on \texttt{run\_feedback\_v2}).",
            f"    Paired W/L/T {wlt} ($\\Delta{delta_tex}$\\,pp).",
            f"    Of {n_wins} wins, {zero_a} have \\texttt{{test\\_only}} Conf$=0$ (rescue regime).",
            f"    Sampled IR records on win tasks: violation\\_type {vtype_str};",
            f"    scenario\\_index {scen_str} (catch-all \\texttt{{others}}).",
            r"    Scope: scenario-indexed IR beats unstructured dumps under headroom;",
            r"    this table does \emph{not} establish an ordering-precedence mechanism",
            r"    on BENCH-120.}",
            r"  \label{tab:e6-win-profile}",
            r"  \footnotesize",
            r"  \begin{tabular}{@{}lc@{}}",
            r"    \toprule",
            r"    Signal & Value \\",
            r"    \midrule",
            f"    Paired C$-$A (W/L/T) & {wlt} \\\\",
            f"    Mean $\\Delta$Conf.\\ (pp) & ${delta_tex}$ \\\\",
            f"    Wins with \\texttt{{test\\_only}} Conf$=0$ & {zero_a}/{n_wins} \\\\",
            f"    Dominant \\texttt{{violation\\_type}} & {top_v} \\\\",
            f"    Dominant \\texttt{{scenario\\_index}} & {top_s} (\\texttt{{others}}) \\\\",
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
            "",
        ]
    )
    OUT_TEX.write_text(tex, encoding="utf-8")
    print(f"Wrote {OUT_TEX.relative_to(ROOT)}")
    print(f"Wrote {OUT_JSON.relative_to(ROOT)}")
    print(json.dumps(profile, indent=2))


if __name__ == "__main__":
    main()
