#!/usr/bin/env python3
"""Summarize run_real_priority_micro_v1 into table + JSON."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
RUN = ROOT / "artifacts" / "run_real_priority_micro_v1" / "results.jsonl"
OUT_JSON = Path(__file__).resolve().parents[1] / "data" / "processed" / "real_priority_micro_summary.json"
OUT_TEX = Path(__file__).resolve().parents[1] / "tables" / "real_priority_micro.tex"


def conf_of(r: dict) -> float:
    for k in ("strict_formal_conformance", "formal_conformance"):
        if r.get(k) is not None:
            return float(r[k])
    return 0.0


def main() -> None:
    rows = [json.loads(l) for l in RUN.read_text(encoding="utf-8").splitlines() if l.strip()]
    by: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by[str(r.get("mode"))].append(r)

    summary = {}
    for mode, rs in by.items():
        confs = [conf_of(r) for r in rs]
        stricts = [float(r.get("strict_success") or r.get("success") or 0) for r in rs]
        # success may be bool
        strict_rate = []
        for r in rs:
            if "strict_formal_conformance" in r:
                strict_rate.append(1.0 if float(r["strict_formal_conformance"]) >= 1.0 - 1e-9 else 0.0)
            elif "success" in r:
                strict_rate.append(1.0 if r["success"] else 0.0)
            else:
                strict_rate.append(0.0)
        calls = [float(r.get("llm_calls") or r.get("n_llm_calls") or 0) for r in rs]
        summary[mode] = {
            "n": len(rs),
            "mean_conf": sum(confs) / len(confs) if confs else 0.0,
            "mean_strict": sum(strict_rate) / len(strict_rate) if strict_rate else 0.0,
            "mean_llm_calls": sum(calls) / len(calls) if calls else 0.0,
        }

    # paired M_eq vs B2
    b2 = {r["task_id"]: conf_of(r) for r in by.get("B2", []) if "task_id" in r}
    # alternate key
    if not b2:
        b2 = {r.get("taskId") or r.get("task"): conf_of(r) for r in by.get("B2", [])}
    meq = {r.get("task_id") or r.get("taskId") or r.get("task"): conf_of(r) for r in by.get("M_eq", [])}
    # unify keys from raw
    def tid(r):
        return r.get("task_id") or r.get("taskId") or r.get("task")

    b2 = {tid(r): conf_of(r) for r in by.get("B2", [])}
    meq = {tid(r): conf_of(r) for r in by.get("M_eq", [])}
    w = l = t = 0
    for k in sorted(set(b2) & set(meq)):
        d = meq[k] - b2[k]
        if d > 1e-9:
            w += 1
        elif d < -1e-9:
            l += 1
        else:
            t += 1
    summary["paired_M_eq_vs_B2"] = {"wins": w, "losses": l, "ties": t}

    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    def pct(mode: str, key: str) -> str:
        return f"{100.0 * summary[mode][key]:.1f}"

    def calls(mode: str) -> str:
        return f"{summary[mode]['mean_llm_calls']:.2f}"

    wlt = summary["paired_M_eq_vs_B2"]
    tex = f"""% Auto-generated by summarize_real_priority_micro.py
\\begin{{table}}[t]
  \\centering
  \\caption{{\\textbf{{Real-priority micro-benchmark}}
    (\\texttt{{real\\_priority\\_micro\\_v1}}, $n{{=}}{summary.get('B2', summary.get('B1', {})).get('n', 30)}$; equal $K{{=}}3$,
    \\texttt{{ecnu-plus}}).
    Curated ACL / billing / routing / firewall / role-gate / tax-bracket
    tasks from industrial patterns, GitHub \\texttt{{.asfl}} harvest, HKCA09,
    and published-industrial pilots---not HardSynthetic generators.
    Lead reading: external validity for C4 (Accept/FAR deployment), not a
    Conf.\\ crown over B2.}}
  \\label{{tab:real-priority-micro}}
  \\footnotesize
  \\renewcommand{{\\arraystretch}}{{1.12}}
  \\begin{{tabular}}{{@{{}}lcccc@{{}}}}
    \\toprule
    Mode & Mean Conf.\\ (\\%) & Strict (\\%) & vs.\\ B2 (W/L/T) & Mean llm\\_calls \\\\
    \\midrule
    B1 & {pct('B1','mean_conf')} & {pct('B1','mean_strict')} & --- & {calls('B1')} \\\\
    B2 & {pct('B2','mean_conf')} & {pct('B2','mean_strict')} & --- & {calls('B2')} \\\\
    \\texttt{{M\\_eq}} & {pct('M_eq','mean_conf')} & {pct('M_eq','mean_strict')} & {wlt['wins']}/{wlt['losses']}/{wlt['ties']} & {calls('M_eq')} \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    OUT_TEX.write_text(tex, encoding="utf-8")
    print(json.dumps(summary, indent=2))
    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
