#!/usr/bin/env python3
"""Summarize external prevention Screen/FAR + write TeX tables."""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXT = ROOT / "artifacts" / "run_prevention_external_v1"
TABLES = ROOT / "paper" / "hsp-agile" / "tables"
PROC = ROOT / "paper" / "hsp-agile" / "data" / "processed"

LABELS = {
    "github_harvest_screen_v1": ("GitHub harvest", 48),
    "hkca09_screen_v1": ("HKCA09 FSF", 35),
    "pubind_pilot_screen_v1": ("Published-industrial pilot", 28),
}


def pct(x: float | None) -> str:
    return f"{100 * x:.1f}" if x is not None else "n/a"


def screen_hits(jsonl: Path) -> list[dict]:
    rows = [json.loads(l) for l in jsonl.read_text(encoding="utf-8").splitlines() if l.strip()]
    by: dict[tuple, dict] = defaultdict(dict)
    for r in rows:
        if r.get("eval_type") != "impl_screening":
            continue
        by[(r["task_id"], r["mutant_id"], r["operator"])][r["mode"]] = r
    hits = []
    for (task_id, mutant_id, op), modes in by.items():
        b2, m, a2 = modes.get("B2"), modes.get("M"), modes.get("A2")
        if b2 and m and b2.get("accepted") and not m.get("accepted"):
            hits.append(
                {
                    "task_id": task_id,
                    "mutant_id": mutant_id,
                    "operator": op,
                    "description": b2.get("description"),
                    "b2_strict": b2.get("strict_conformance"),
                    "m_strict": m.get("strict_conformance"),
                    "a2_accepted": bool(a2.get("accepted")) if a2 else None,
                }
            )
    return hits


def esc(s: str) -> str:
    return (s or "").replace("_", "\\_").replace("%", "\\%")


def main() -> None:
    summaries = json.loads((EXT / "external_screen_summary.json").read_text(encoding="utf-8"))
    tex_rows = []
    for key, (lab, n) in LABELS.items():
        far = summaries[key]["impl_screening"]
        tex_rows.append(
            f"    {lab} & {n} & {summaries[key]['n_screen_hits']} & "
            f"{pct(far.get('B2', {}).get('false_accept_rate'))}\\% & "
            f"{pct(far.get('A2', {}).get('false_accept_rate'))}\\% & "
            f"{pct(far.get('M', {}).get('false_accept_rate'))}\\% \\\\"
        )
    table = "\n".join(
        [
            "% Auto-generated by scripts/summarize_external_screen.py",
            r"\begin{table}[t]",
            r"  \centering",
            r"  \caption{External impl-screening (reference mutants; B2/A2/M).",
            r"    Screen-hits = mutants accepted by B2 but rejected by M.",
            r"    Industrial-132 remains the primary Screen evidence; external rows are",
            r"    reproducible extensions or saturation boundaries.}",
            r"  \label{tab:e2-ext-screen}",
            r"  \footnotesize",
            r"  \begin{tabular}{@{}lrrrrr@{}}",
            r"    \toprule",
            r"    Corpus & $n$ tasks & Screen-hits & FAR B2 & FAR A2 & FAR M \\",
            r"    \midrule",
            *tex_rows,
            r"    \bottomrule",
            r"  \end{tabular}",
            r"\end{table}",
            "",
        ]
    )
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "e2_ext_screen.tex").write_text(table, encoding="utf-8")

    hits = screen_hits(EXT / "github_harvest_screen_v1" / "prevention_eval.jsonl")
    ops = Counter(h["operator"] for h in hits)
    PROC.mkdir(parents=True, exist_ok=True)
    (PROC / "e2_screen_vignette_external.json").write_text(
        json.dumps(
            {
                "source": "artifacts/run_prevention_external_v1/github_harvest_screen_v1/prevention_eval.jsonl",
                "n_screen_hits": len(hits),
                "operator_counts": dict(ops),
                "vignettes": hits,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    picks: list[dict] = []
    for want in ("DRO", "MBO", "WRO"):
        for v in hits:
            if v["operator"] == want and v not in picks:
                picks.append(v)
                break
    while len(picks) < 3 and len(hits) > len(picks):
        for v in hits:
            if v not in picks:
                picks.append(v)
            if len(picks) >= 3:
                break
    rows_tex = " \\\\\n".join(
        f"{esc(v['task_id'])} & {v['operator']} & {esc((v.get('description') or '')[:48])} & "
        f"B2 accept, M reject"
        for v in picks
    )
    vtex = f"""% Auto-generated external Screen vignettes (GitHub harvest)
\\begin{{table}}[t]
  \\centering
  \\caption{{External Screen-hit vignettes on GitHub harvest reference mutants
    ($n{{=}}{len(hits)}$ B2-accept / M-reject). Reproducible extension of industrial
    Screen; not a replacement for industrial-132.}}
  \\label{{tab:e2-screen-vignette-ext}}
  \\footnotesize
  \\begin{{tabular}}{{@{{}}lll@{{ }}p{{0.28\\linewidth}}@{{}}}}
    \\toprule
    Task & Op & Defect sketch & Gate outcome \\\\
    \\midrule
{rows_tex} \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""
    (TABLES / "e2_screen_vignette_external.tex").write_text(vtex, encoding="utf-8")
    print(json.dumps({"table": "e2_ext_screen.tex", "github_hits": len(hits), "ops": dict(ops)}, indent=2))


if __name__ == "__main__":
    main()
